# Generated by Django 3.0.5 on 2020-05-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200523_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePost',
            fields=[
                ('posts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Posts')),
            ],
            bases=('blog.posts',),
        ),
    ]
