# Generated by Django 3.0.5 on 2020-05-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_updatepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatePost',
        ),
    ]
